#-------------------------------------------------------------------------------
#SpringBoot
info:
  component: Aplicación demo SpringBoot-Starter-2.1.6, ICC-Config y GraphQL
  version: ${application.container.version}
#-------------------------------------------------------------------------------
target:
  platform: demotarget
application:
  id: ${spring.application.name}
  env: development
  version: 1.0
  container:
    version: 1.0
server:
  port: 8098
  servlet:
    context-path: /${application.env}/demoapp
graphiql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
spring:
  application:
    name: demoapplication
  boot:
    admin:
      # url: http://172.31.80.90:8106/${app.env}/boot-manager
      #client:
       # prefer-ip: true   
  rabbitmq:
    host: ${docker.rabbitmq-log.ip}
    port: ${docker.rabbitmq-log.port}
    username: ${docker.rabbitmq-log.user}
    password: ${docker.rabbitmq-log.password}   
  jpa:
    hibernate:
      enable_lazy_load_no_trans: true
    open-in-view: true    
logging:  
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.data: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
test:
  adry: Adriana
  man: Manfredo
#-------------------------------------------------------------------------------
#Containers
docker:
  redis:
    ip: 192.168.1.75
    port: 4379
  redis-platform:
    ip: 192.168.1.75
    port: 4379
  rabbitmq-log:
    ip: 192.168.1.75
    port: 4672
    user: guest
    password: guest
cache:
  db:
    configentry: 0
    list: db0
    db0:
      ip: ${docker.redis-platform.ip}
      port: ${docker.redis-platform.port}
      channel:
        name: refresh-channel
management:
  security:
    enabled: false
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true
  #logfile:
    #external-file: ${app.log}/${spring.application.name}/${spring.cloud.client.ipAddress}-${server.port}-infra.log
  jmx:
    enabled: true
  jolokia:
    enabled: true